# Write your MySQL query statement below
SELECT s.STUDENT_ID, S.STUDENT_NAME, SUB.SUBJECT_NAME, COUNT(E.SUBJECT_NAME) AS attended_exams
FROM STUDENTS S
CROSS JOIN SUBJECTS SUB
LEFT JOIN EXAMINATIONS E ON SUB.SUBJECT_NAME = E.SUBJECT_NAME AND S.STUDENT_ID = E.STUDENT_ID
GROUP BY STUDENT_ID, STUDENT_NAME, SUBJECT_NAME
ORDER BY STUDENT_ID, STUDENT_NAME, SUBJECT_NAME