# Write your MySQL query statement below
-- SELECT CUSTOMER_NUMBER
-- FROM ORDERS
-- GROUP BY CUSTOMER_NUMBER
-- ORDER BY COUNT(*) DESC
-- LIMIT 1
WITH CTE AS(
    SELECT CUSTOMER_NUMBER,
    RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
    FROM ORDERS
    GROUP BY CUSTOMER_NUMBER
)
SELECT CUSTOMER_NUMBER
FROM CTE
WHERE RNK = 1